[package]
name = "hashing-felts"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm.workspace = true
hashing-felts-methods = { path = "../../methods/hashing-felts-methods" }
core = { path = "../../methods/core" }
starknet-core = "=0.12.1"
common = { path = "../../common" }
