[package]
name = "neg-log-fixed-core"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
serde = { version = "1.0", default-features = false }
simba = { version = "0.9.0", features = [
  "partial_fixed_point_support",
  "serde_serialize",
] }

