[package]
name = "proof-composition-twap-maxreturn-reserveprice-floating-hashing-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "=1.2.5", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
remove-seasonality-error-bound-floating-methods = { path = "../../remove-seasonality-error-bound-floating-methods" }
simulate-price-verify-position-floating-methods = { path = "../../simulate-price-verify-position-floating-methods" }
add-twap-7d-error-bound-floating-methods = { path = "../../add-twap-7d-error-bound-floating-methods" }
calculate-pt-pt1-error-bound-floating-methods = { path = "../../calculate-pt-pt1-error-bound-floating-methods" }
twap-error-bound-floating-methods = { path = "../../twap-error-bound-floating-methods" }
max-return-floating-methods = { path = "../../max-return-floating-methods" }
hashing-felts-methods = { path = "../../hashing-felts-methods" }

core = { path = "../../core" }
guest-fixed-utils = { git = "https://github.com/OilerNetwork/fossil-light-client.git", branch = "sepolia-deployment", package = "guest-fixed-utils" }