[package]
name = "remove-seasonality-error-bound-floating"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "=2.0.0" }
core = { path = "../../methods/core" }
remove-seasonality-error-bound-floating-methods = { path = "../../methods/remove-seasonality-error-bound-floating-methods" }
common = { path = "../../common", features = ["original"] }
