[package]
name = "twap-error-bound-floating"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.1.2" }
twap-error-bound-floating-methods = { path = "./methods" }
twap-error-bound-floating-core = { path = "./core" }