[package]
name = "proof-composition-twap-maxreturn-reserveprice-floating-hashing-core"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
serde = { version = "1.0", default-features = false }
