[package]
name = "calculate-reserve-price-from-simulated-log-prices-floating-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
benchmark = { path = "../../../../benchmark" }
calculate-reserve-price-from-simulated-log-prices-floating-core = { path = "../../core" }