[package]
name = "reserve-price-floating-composition-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
remove-seasonality-floating-methods = { path = "../../../remove-seasonality-floating/methods" }
simulate-price-floating-methods = { path = "../../../simulate-price-floating/methods" }
add-twap-7d-floating-methods = { path = "../../../add-twap-7d-floating/methods" }
reserve-price-floating-methods = { path = "../../../reserve-price-floating/methods" }
reserve-price-floating-core = { path = "../../../reserve-price-floating/core" }

reserve-price-floating-composition-core = { path = "../../core" }
