[package]
name = "simulate-price-verify-position-floating2-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.1.2" }

[package.metadata.risc0]
methods = ["guest"]
