[package]
name = "max-return-floating-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "=1.2.4", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
benchmark = { path = "../../../../benchmark" }
max-return-floating-core = { path = "../../core" }
