[package]
name = "simulate-price-verify-position-floating-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "=1.2.4", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
common = { path = "../../../../common" }
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
simulate-price-verify-position-floating-core = { path = "../../core" }