[package]
name = "max-return-floating-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "=1.2.5", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
common = { path = "../../../../common" }
max-return-floating-core = { path = "../../core" }
