[package]
name = "remove-seasonality-error-bound-floating-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "=1.2.4", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
common = { path = "../../../../common" }
remove-seasonality-error-bound-floating-core = { path = "../../core" }