[package]
name = "mock-proof-composition"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "=1.2.5" }

guest-fixed-utils = { git = "https://github.com/OilerNetwork/fossil-light-client.git", branch = "sepolia-deployment", package = "guest-fixed-utils" }
mock-proof-composition-core = { path = "./core" }
mock-proof-composition-methods = { path = "./methods" }