[package]
name = "simulate-price-verify-position-floating-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "=2.1.0", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
common = { path = "../../../common" }
core = { path = "../../core" }