[package]
name = "twap-error-bound-floating"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm.workspace = true
twap-error-bound-floating-methods = { path = "../../methods/twap-error-bound-floating-methods" }
core = { path = "../../methods/core" }
common = { path = "../../common", features = ["original"] }