[package]
name = "hashing-felts"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "=1.2.5" }
hashing-felts-methods = { path = "methods" }
hashing-felts-core = { path = "core" }
starknet-core = "=0.12.1"
common = { path = "../../common" }
