[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false }
fixed = { version = "1.28.0", features = ["serde"] }
simba = { version = "0.9.0", features = ["partial_fixed_point_support", "serde_serialize"] }

