[package]
name = "add-twap-7d-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
benchmark = { path = "../../../../benchmark" }
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }