[package]
name = "neg-log-fixed-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
neg-log-fixed-core = { path = "../../core" }
benchmark = { path = "../../../../benchmark" }
