[package]
name = "mrjpdf-floating-core"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
serde = { version = "1.0", default-features = false }
simba = { version = "0.9.0", features = ["serde_serialize"] }
