[package]
name = "mock-proof-composition-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "2.3.1", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
core = { path = "../../core" }
guest-fixed-utils = { git = "https://github.com/OilerNetwork/fossil-light-client.git", branch = "sepolia-deployment", package = "guest-fixed-utils" }

# Optional method dependencies - enable with features
remove-seasonality-error-bound-floating-methods = { path = "../../remove-seasonality-error-bound-floating-methods", optional = true }
simulate-price-verify-position-floating-methods = { path = "../../simulate-price-verify-position-floating-methods", optional = true }
add-twap-7d-error-bound-floating-methods = { path = "../../add-twap-7d-error-bound-floating-methods", optional = true }
calculate-pt-pt1-error-bound-floating-methods = { path = "../../calculate-pt-pt1-error-bound-floating-methods", optional = true }
twap-error-bound-floating-methods = { path = "../../twap-error-bound-floating-methods", optional = true }
max-return-floating-methods = { path = "../../max-return-floating-methods", optional = true }
hashing-felts-methods = { path = "../../hashing-felts-methods", optional = true }

[features]
default = []
full = [
    "remove-seasonality-error-bound-floating-methods",
    "simulate-price-verify-position-floating-methods", 
    "add-twap-7d-error-bound-floating-methods",
    "calculate-pt-pt1-error-bound-floating-methods",
    "twap-error-bound-floating-methods",
    "max-return-floating-methods",
    "hashing-felts-methods"
]
remove-seasonality = ["remove-seasonality-error-bound-floating-methods"]
simulate-price = ["simulate-price-verify-position-floating-methods"]
twap = ["add-twap-7d-error-bound-floating-methods", "twap-error-bound-floating-methods"]
calculate-pt = ["calculate-pt-pt1-error-bound-floating-methods"]
max-return = ["max-return-floating-methods"]
hashing = ["hashing-felts-methods"]
