[package]
name = "mock-proof-composition-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "=1.2.5", default-features = false, features = [
    'std',
    'getrandom',
    'heap-embedded-alloc',
] }
mock-proof-composition-core = { path = "../../core" }

guest-fixed-utils = { git = "https://github.com/OilerNetwork/fossil-light-client.git", branch = "sepolia-deployment", package = "guest-fixed-utils" }